Closes #26 Request secret dot repository
Why? There are some secrets we need keep out of the public dot
repository.

How? Give option to configure a new repository at .dot-secrets to be
used later for public dotfiles scripts.

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,6 +27,29 @@ fail () {
   exit
 }
 
+setup_secret_dotfiles () {
+  local -r dot_secret="$HOME/.dot-secrets"
+
+  if ! [[ -d "${dot_secret}" || -L "${dot_secret}" ]]
+  then
+    info 'setup dotfiles secrets'
+
+    user ' - What is your github secrets repo URL?'
+    read -e github_secrets_repo
+
+    git ls-remote "$github_secrets_repo" &>-
+    if [ "$?" -ne 0 ]; then
+        fail "Unable to read from '$github_secrets_repo'"
+    fi
+
+    git clone "$github_secrets_repo" "$dot_secret"
+
+    success 'Secrets Repo'
+
+  fi
+}
+
+
 setup_gitconfig () {
   if ! [ -f git/gitconfig.symlink ]
   then
@@ -138,6 +161,7 @@ install_dotfiles () {
 }
 
 setup_gitconfig
+setup_secret_dotfiles
 install_dotfiles
 
 # If we're on a Mac, let's install and setup homebrew.
